### ISSUE TITLE
Incorrect isbn after ean13

### ISSUE THREAD

**Issue by dag-odoo** [xlcnd/isbnlib-bnf#1]
Hello,

First of all, thanks for this great plugin.
I get empty result when I try to search for ISBN 2-8001-2133-5 using meta function from isbnlib.
After further investigation, I found it comes from the query function from isbnlib, converting isbn into EAN13. (2-8001-2133-5 to 9782800121338)
This does not seem to work with your current query function in _bnf.

However, when I use your query from _bnf with the isbn  2-8001-2133-5 directly, the answer is not empty and I get good results.

I also noticed that the parsing of authors is incomplete. For this isbn, the authors are coma separated.

Possible fix is to do the search on ean field instead of isbn, since isbnlib always do the conversion.

Best regards,

**Comment by xlcnd** [comment]
Hi,

This is one (of many) inconsistency problems of the BnF api! I have already found a 'solution' (querying at the same time with isbn10 and isbn13) and is implemented in the dev branch.

In relation to the 'Authors' field, in order to keep the same criteria of other providers, illustrators, traductors, commentators, ... are NOT considered Authors.

Thanks.

**Comment by dag-odoo** [comment]
Hello,
Thanks for the quick answer. I'm currently testing it, it seems to work fine. I still don't get why bnf sends xml instead of json.

Thanks again for the fix, I think you can close the issue :)
